name = "Overly Optimized"
author = "Cartrigger"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60e3ad4649d7cd161ecdf39341fe81d20beb30d114992e1bace92230a7ebf752"

[versions]
fabric = "0.16.14"
minecraft = "1.21.6"
