name = "Overly Optimized"
author = "Cartrigger"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f324f633105554932ac822fc675502c33b569a0829d2dd8808f5217025e1bc5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.7"
