name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36b832196ef6af89779bb975ce909113460903a6d1758283de7aeb39b2acf81f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
