name = "Overly Optimized"
author = "Cartrigger"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39e5802eb6b7675a992cf7cd0cd1caf2a0c4a295a21f0dbfc5b5d6599a8c2949"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
