name = "Overly Optimized"
author = "Cartrigger"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfdab9f292a3813fe473ee900fcf60788f47499d28971d136994f084a86372f8"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
