name = "Overly Optimized"
author = "Cartrigger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5f3c2a4e9a166135a74d2ae07023f333a49ff2ecf7c9df778995dd273dafa4"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
