name = "Overly Optimized"
author = "Cartrigger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74fadbf8424b51eebca6327cb7c1455eb8d6d2a2f0a42bca342cedb92c96eea7"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
