name = "Overly Optimized"
author = "Cartrigger"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92a93de548020f62505803acf14bb58bfb3eb96715c7cdae73a5f99935590f9c"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
