name = "Overly Optimized"
author = "Cartrigger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78badd65887d2c19fb36aea007f97b6b7f87a591313263cfbb3264a5d7578700"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"

[options]
