name = "Overly Optimized"
author = "Cartrigger"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b44c8ffec528bb075b588ee69acc4befb8320a1946d978316a5fe3085f11a08"

[versions]
fabric = "0.16.11"
minecraft = "1.21.1"

[options]
