name = "Overly Optimized"
author = "Cartrigger"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0fceedd246444818a007e3bf04e909df80001cd023d507ca1fd179d522bc8ad5"

[versions]
fabric = "0.16.10"
minecraft = "1.21.5"
